version: "3.4"
services:
  app:
    image: node:12-buster-slim
    entrypoint: /bin/sleep infinity
    working_dir: /usr/src/app/
    volumes:
      - "../app:/usr/src/app:cached"
    environment:
      - DNSDOCK_ALIAS=node-dev.bmeme.docker
